### ISSUE TITLE
Unable to run spoon with multiple devices attached (OSX)

### ISSUE THREAD

**Issue by TealOcean** [x2on/gradle-spoon-plugin#6]
So I'm getting this error when I attach more than 1 device and run spoon with this plugin:

STDERR Error: Could not find or load main class com.squareup.spoon.SpoonDeviceRunner

My setup is:
OSX 10.9 Mavericks
Android Studio 0.5
Android Gradle Plugin 0.9
Spoon Gradle Plugin 1.1.2
Spoon 1.1.1
Robotium 5.0.1

This only occurs with more than 1 device attached.

**Comment by itsmortoncornelius** [comment]
I had the same problem. My problem was that I also included "com.squareup.spoon:spoon-runner:1.1.2" as dependency. After looking into your project I removed it from my dependencies and everything worked well.

**Comment by itsmortoncornelius** [comment]
I have the same error. Your example project runs without any problem.
The difference is that I'm using EspressoTests. My build.gradle is the following:

In the global file I apply
classpath 'de.felixschulze.gradle:gradle-spoon-plugin:2.0'

In my module's file:
apply plugin: 'de.felixschulze.gradle.spoon'

spoon {
    debug = true
    failIfNoDeviceConnected = false
}

dependencies {
    // test ui screen shots with spoon
    compile 'com.squareup.spoon:spoon-client:1.1.2'
    compile 'com.squareup.spoon:spoon-runner:1.1.2'
}

**Comment by x2on** [comment]
did you try to remve the spoon-runner dependency?

**Comment by itsmortoncornelius** [comment]
yes, I tried that. Isn't it necessary?

**Comment by itsmortoncornelius** [comment]
Still no idea? I still have the problem also without the spoon-runner dependency and the updated plugin version 2.1

**Comment by x2on** [comment]
@itsmortoncornelius could you please run with `--debug` and post the output here?

**Comment by mmartin101** [comment]
I too am having this issue on OSX with two emulators

**Comment by x2on** [comment]
@mmartin101 could you please run with `--debug` and post the output here?

**Comment by itsmortoncornelius** [comment]
Sorry for the silence,
the output is the following:

"10:11:00.784 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:_compileDebugAndroidTestJava'
10:11:00.790 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':presentation:_compileDebugAndroidTestJava' is up-to-date
10:11:00.799 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Skipping task ':presentation:_compileDebugAndroidTestJava' as it is up-to-date (took 0.007 secs).
10:11:00.810 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:_compileDebugAndroidTestJava'
10:11:00.810 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:_compileDebugAndroidTestJava UP-TO-DATE
10:11:00.813 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:_compileDebugAndroidTestJava (Thread[main,5,main]) completed. Took 0.029 secs.
10:11:00.813 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:compileRetrolambdaDebugAndroidTest (Thread[main,5,main]) started.
10:11:00.833 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:compileRetrolambdaDebugAndroidTest
10:11:00.833 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:compileRetrolambdaDebugAndroidTest'
10:11:00.842 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':presentation:compileRetrolambdaDebugAndroidTest' is up-to-date
10:11:00.847 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Skipping task ':presentation:compileRetrolambdaDebugAndroidTest' as it is up-to-date (took 0.003 secs).
10:11:00.847 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:compileRetrolambdaDebugAndroidTest'
10:11:00.848 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:compileRetrolambdaDebugAndroidTest UP-TO-DATE
10:11:00.851 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:compileRetrolambdaDebugAndroidTest (Thread[main,5,main]) completed. Took 0.018 secs.
10:11:00.851 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:preDexDebugAndroidTest (Thread[main,5,main]) started.
10:11:00.851 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:preDexDebugAndroidTest
10:11:00.870 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:preDexDebugAndroidTest'
10:11:00.876 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':presentation:preDexDebugAndroidTest' is up-to-date
10:11:00.880 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Skipping task ':presentation:preDexDebugAndroidTest' as it is up-to-date (took 0.001 secs).
10:11:00.896 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:preDexDebugAndroidTest'
10:11:00.896 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:preDexDebugAndroidTest UP-TO-DATE
10:11:00.899 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:preDexDebugAndroidTest (Thread[main,5,main]) completed. Took 0.048 secs.
10:11:00.899 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:dexDebugAndroidTest (Thread[main,5,main]) started.
10:11:00.903 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:dexDebugAndroidTest
10:11:00.903 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:dexDebugAndroidTest'
10:11:00.908 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':presentation:dexDebugAndroidTest' is up-to-date
10:11:00.914 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Skipping task ':presentation:dexDebugAndroidTest' as it is up-to-date (took 0.002 secs).
10:11:00.915 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:dexDebugAndroidTest'
10:11:00.918 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:dexDebugAndroidTest UP-TO-DATE
10:11:00.918 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:dexDebugAndroidTest (Thread[main,5,main]) completed. Took 0.015 secs.
10:11:00.921 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:processDebugAndroidTestJavaRes (Thread[main,5,main]) started.
10:11:00.921 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:processDebugAndroidTestJavaRes
10:11:00.921 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:processDebugAndroidTestJavaRes'
10:11:00.931 [INFO] [org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter] Skipping task ':presentation:processDebugAndroidTestJavaRes' as it has no source files.
10:11:00.948 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:processDebugAndroidTestJavaRes'
10:11:00.948 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:processDebugAndroidTestJavaRes UP-TO-DATE
10:11:00.951 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:processDebugAndroidTestJavaRes (Thread[main,5,main]) completed. Took 0.03 secs.
10:11:00.951 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:packageDebugAndroidTest (Thread[main,5,main]) started.
10:11:00.954 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:packageDebugAndroidTest
10:11:00.954 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:packageDebugAndroidTest'
10:11:00.974 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':presentation:packageDebugAndroidTest' is up-to-date
10:11:00.979 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Skipping task ':presentation:packageDebugAndroidTest' as it is up-to-date (took 0.002 secs).
10:11:00.980 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:packageDebugAndroidTest'
10:11:00.998 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:packageDebugAndroidTest UP-TO-DATE
10:11:00.998 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:packageDebugAndroidTest (Thread[main,5,main]) completed. Took 0.044 secs.
10:11:01.000 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:assembleDebugAndroidTest (Thread[main,5,main]) started.
10:11:01.001 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:assembleDebugAndroidTest
10:11:01.001 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:assembleDebugAndroidTest'
10:11:01.010 [INFO] [org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter] Skipping task ':presentation:assembleDebugAndroidTest' as it has no actions.
10:11:01.013 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':presentation:assembleDebugAndroidTest'
10:11:01.013 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:assembleDebugAndroidTest UP-TO-DATE
10:11:01.016 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:assembleDebugAndroidTest (Thread[main,5,main]) completed. Took 0.016 secs.
10:11:01.016 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :presentation:spoonDebugAndroidTest (Thread[main,5,main]) started.
10:11:01.034 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :presentation:spoonDebugAndroidTest
10:11:01.034 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':presentation:spoonDebugAndroidTest'
10:11:01.039 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':presentation:spoonDebugAndroidTest' is up-to-date
10:11:01.044 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':presentation:spoonDebugAndroidTest' (up-to-date check took 0.002 secs) due to:
  Task.upToDateWhen is false.                       
10:11:01.046 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':presentation:spoonDebugAndroidTest'.
10:11:01.537 [QUIET] [system.out] 2015-03-27 10:11:01 [SR.runTests] Executing instrumentation suite on 2 device(s).
10:11:01.546 [QUIET] [system.out] 2015-03-27 10:11:01 [SR.runTests] Application: de.company.android.presentation from /Users/user/Development/android/Project/presentation/build/outputs/apk/presentation-debug.apk
10:11:01.547 [QUIET] [system.out] 2015-03-27 10:11:01 [SR.runTests] Instrumentation: de.company.android.presentation.test from /Users/user/Development/android/Project/presentation/build/outputs/apk/presentation-debug-androidTest-unaligned.apk
10:11:01.555 [QUIET] [system.out] 2015-03-27 10:11:01 [SR.runTests] [CC49RWX02081] Starting execution.
10:11:01.558 [QUIET] [system.out] 2015-03-27 10:11:01 [SR.runTests] [02a9779d] Starting execution.
10:11:01.558 [QUIET] [system.out] 2015-03-27 10:11:01 [SDR.runInNewProcess] [02a9779d]
10:11:01.558 [QUIET] [system.out] 2015-03-27 10:11:01 [SDR.runInNewProcess] [CC49RWX02081]
10:11:01.698 [QUIET] [system.out] 2015-03-27 10:11:01 [SDR.printStream] [02a9779d] STDERR Fehler: Hauptklasse com.squareup.spoon.SpoonDeviceRunner konnte nicht gefunden oder geladen werden
10:11:01.698 [QUIET] [system.out] 2015-03-27 10:11:01 [SDR.printStream] [CC49RWX02081] STDERR Fehler: Hauptklasse com.squareup.spoon.SpoonDeviceRunner konnte nicht gefunden oder geladen werden
10:11:01.699 [QUIET] [system.out] 2015-03-27 10:11:01 [SDR.runInNewProcess] Process.waitFor() finished for [02a9779d] with exitCode 1
10:11:01.699 [QUIET] [system.out] 2015-03-27 10:11:01 [SDR.runInNewProcess] Process.waitFor() finished for [CC49RWX02081] with exitCode 1
10:11:01.720 [QUIET] [system.out] 2015-03-27 10:11:01 [SR$1.run] [02a9779d] Execution done. (0 remaining [CC49RWX02081])
10:11:01.720 [QUIET] [system.out] 2015-03-27 10:11:01 [SR$1.run] [CC49RWX02081] Execution done. (0 remaining [])
10:11:02.175 [DEBUG] [rhino] [  Envjs/1.6 (Rhino; U; Mac OS X x86_64 10.10.2; en-US; rv:1.7.0.rc2) Resig/20070309 PilotFish/1.2.13  ]
10:11:02.204 [DEBUG] [org.lesscss.LessCompiler] Finished initialization of LESS compiler in 469 ms.
10:11:02.440 [DEBUG] [org.lesscss.LessCompiler] Finished compilation of LESS source in 236 ms."

**Comment by x2on** [comment]
@itsmortoncornelius looks like the issue comes directly from spoon 

Output from Spoon:

```
 [SDR.printStream] [CC49RWX02081] STDERR Fehler: Hauptklasse com.squareup.spoon.SpoonDeviceRunner konnte nicht gefunden oder geladen werden
```

Here is a simular bug report on the spoon project: https://github.com/square/spoon/issues/177
